#prefix used to show up metrics in AppDynamics
metricPrefix: "Custom Metrics|Solr"

#This will create it in specific Tier. Replace <TIER_ID>
#metricPrefix:  "Server|Component:<TIER_ID>|Custom Metrics|Solr Monitor|"

servers:
   - host: "localhost"
     port: 8983
     # Optional Parameters. Configure if any required
     name: "Solr Monitor 1"
     username: ""
     password: ""
     contextRoot: ""
     usessl: ""
     proxyHost: ""
     proxyPort: ""
     proxyUsername: ""
     proxyPassword: ""
   - host: "localhost"
     port: 8983
     # Optional Parameters. Configure if any required
     name: "Solr Monitor 2"
     username: ""
     password: ""
     contextRoot: ""
     usessl: ""
     proxyHost: ""
     proxyPort: ""
     proxyUsername: ""
     proxyPassword: ""

# Example
# cores
# - name: "collection1"
#     pingHandler: "/admin/ping"
#     queryHandlers: ["/select", "/update"]
#   - name: "collection2"
#     pingHandler: "/admin/ping"
#     queryHandlers: ["/admin/ping"]
cores:
    - name: "gettingstarted"
      pingHandler: "/admin/ping"
      queryHandlers: ["/select", "/update"]
    - name: ""
      pingHandler: "/admin/ping"
      queryHandlers: []

numberOfThreads: 5


