#prefix used to show up metrics in AppDynamics (not recommended)
#metricPrefix: "Custom Metrics|Solr"

#This will create it in specific Tier. Replace <TIER_ID>
metricPrefix: "Server|Component:<TIER_ID>|Custom Metrics|Solr Monitor|"

servers:
    # mandatory parameters
   - host: "localhost"
     port: 8983
     name: "Server 1"
     collectionName : "gettingStarted"

#  Optional Parameters. Configure if any required
#     username: ""
#     password: ""
#     contextRoot: ""
#     usessl: ""
#     proxyHost: ""
#     proxyPort: ""
#     proxyUsername: ""
#     proxyPassword: ""


#   - host: "localhost"
#     port: 7574
#     name: "Server 2"
#     collectionName : "techproducts"



metricCharacterReplacer:
   - replace: "%"
     replaceWith: ""
   - replace: ","
     replaceWith: "-"
   - replace: "."
     replaceWith: "-"

numberOfThreads: 5
