
server:
    host: "localhost"
    port: 8983
    # Optional Parameters. Configure if any required
    username: ""
    password: ""
    contextRoot: ""
    usessl: ""
    proxyHost: ""
    proxyPort: ""
    proxyUsername: ""
    proxyPassword: ""
    
# Example
# cores
# - name: "collection1"
#     queryHandlers: ["/select", "/update"]
#   - name: "collection2"
#     queryHandlers: ["/admin/ping"]
cores:
   - name: ""
     queryHandlers: []
   - name: ""
     queryHandlers: []

#prefix used to show up metrics in AppDynamics
metricPrefix:  "Custom Metrics|Solr|"

