#prefix used to show up metrics in AppDynamics
metricPrefix: "Custom Metrics|Solr"

#This will create it in specific Tier. Replace <TIER_ID>
#metricPrefix: "Server|Component:11 |Custom Metrics|Solr Monitor|"

servers:
   - host: "localhost"
     port: 8983
     name: "Solr Monitor 1" #optional if only one server
     # Optional Parameters. Configure if any required
     username: ""
     password: ""
     contextRoot: ""
     usessl: ""
     proxyHost: ""
     proxyPort: ""
     proxyUsername: ""
     proxyPassword: ""
   - host: "localhost"
     port: 8983
     name: "Solr Monitor 2" #optional if only one server
     # Optional Parameters. Configure if any required
#     username: ""
#     password: ""
#     contextRoot: ""
#     usessl: ""
#    proxyHost: ""
#     proxyPort: ""
#     proxyUsername: ""
#     proxyPassword: ""

# Example
# cores
# - name: "collection1"
#     pingHandler: "/admin/ping"
#     queryHandlers: ["/select", "/update"]
#   - name: "collection2"
#     pingHandler: "/admin/ping"
#     queryHandlers: ["/admin/ping"]
cores:
   - name: "gettingstarted"
     pingHandler: "/admin/ping"
     queryHandlers: ["/select", "/update"]

numberOfThreads: 5


