#prefix used to show up metrics in AppDynamics (not recommended)
#metricPrefix: "Custom Metrics|Solr"

#This will create it in specific Tier. Replace <TIER_ID>
metricPrefix: "Server|Component:<TIER_ID>|Custom Metrics|Solr Monitor"

servers:
    # mandatory parameters
   - host: ""
     port: 9999
     name: "Server 1"
     collectionName : ["techproducts","gettingstarted"]
     applicationName: "solr"

   - host: ""
     port: 9998
     name: "Server 2"
     collectionName : ["techproducts","gettingstarted"]
     applicationName: "solr"

metricCharacterReplacer:
   - replace: "\\%"
     replaceWith: "\\-"
   - replace: "\\,"
     replaceWith: "\\-"
   - replace: "\\."
     replaceWith: "\\-"

numberOfThreads: 5

# If any of the following fields are not set, the values of the specific fields are set from the system properties of the corresponding fields as specified in the comments.
# If the system properties are not set for the field, then the data is retrieved from machine agent configFile. Please refer to ControllerInfoFactory for more details.
# Values provided here can be overridden if the same field is configured in either controller-info.xml or system properties.
controllerInfo:
  controllerHost: ""  # -Dappdynamics.controller.hostName
  controllerPort:  # -Dappdynamics.controller.port
  controllerSslEnabled: false # -Dappdynamics.controller.ssl.enabled
  enableOrchestration: false # N/A
  uniqueHostId: "" # -Dappdynamics.agent.uniqueHostId
  username: "admin" # -Dappdynamics.agent.monitors.controller.username
  password: "" # -Dappdynamics.agent.monitors.controller.password
  encryptedPassword: "j+0oxTzUtw2xAdaq4UUq/Q==" # -Dappdynamics.agent.monitors.controller.encryptedPassword
  accountAccessKey: "" # -Dappdynamics.agent.accountAccessKey
  account: "" # -Dappdynamics.agent.accountName
  machinePath: "" # -Dappdynamics.machine.agent.hierarchyPath
  simEnabled: false # -Dappdynamics.sim.enabled
  applicationName: "" # -Dappdynamics.agent.applicationName
  tierName: "" # -Dappdynamics.agent.tierName
  nodeName: "" # -Dappdynamics.agent.nodeName

#Encryption key for your controllerInfo password
encryptionKey: "abcd"